### ISSUE TITLE
sftp doesnt works

### ISSUE THREAD

**Issue by xwulfus** [welaika/photocopier#21]
sftp doesnt works

**Comment by pioneerskies** [comment]
To be more specific: SFTP is supported by LFTP, but it is implemented only for folder mirroring and not for file up/download or deletion.

I've pushed a new gem version in pre-release, which should do the work fully supporting SFTP. You can try this by upgrading Photocopier gem with

    gem update photocopier --pre

then using wordmove as usual. I'll be glad to receive your feedback and get out of `pre` in the next week (later I'll be on vacation ;) )

Cheers

**Comment by pioneerskies** [comment]
Would you mind to paste here your obfuscated `movefile.yml` in the meantime? Just for quicker reference

**Comment by xwulfus** [comment]
```
`vagrant@USER_SECURE:~/www$ cat movefile.yml 
#global:
#  sql_adapter: wpcli

local:
  vhost: "https://USER_SECURE.local"
  wordpress_path: "/www/SECURE/public_html" # use an absolute path here

  database:
    name: "wordpress"
    user: "wordpress"
    password: "wordpress" # could be blank, so always use quotes around
    host: "localhost"

production:
  vhost: "http://subdomain.superserver.com"
  wordpress_path: public_html/ # use an absolute path here


  database:
    name: "USERDB_SECURE_nl"
    user: "USERDB_SECURE_nl"
    password: "PASS_SECURE"
    host: "localhost"
    # port: 3308 # Use just in case you have exotic server config
    # mysqldump_options: '--max_allowed_packet=1G' # Only available if using SSH
    # mysql_options: '--protocol=TCP' # mysql command is used to import db

  exclude:
    - '.git/'
    - '.gitignore'
    - '.gitmodules'
    - '.env'
    - 'node_modules/'
    - 'bin/'
    - 'tmp/*'
    - 'Gemfile*'
    - 'Movefile'
    - 'movefile'
    - 'movefile.yml'
    - 'movefile.yaml'
    - 'wp-config.php'
    - 'wp-content/*.sql.gz'
    - '*.orig'

  # paths: # you can customize wordpress internal paths
  #   wp_content: wp-content
  #   uploads: wp-content/uploads
  #   plugins: wp-content/plugins
  #   mu_plugins: wp-content/mu-plugins
  #   themes: wp-content/themes
  #   languages: wp-content/languages

  # ssh:
  #   host: host
  #   user: user
  #   password: password # password is optional, will use public keys if available.
  #   port: 22 # Port is optional
  #   rsync_options: '--verbose --itemize-changes' # Additional rsync options, optional
  #   gateway: # Gateway is optional
  #     host: host
  #     user: user
  #     password: password # password is optional, will use public keys if available.

  ftp:
    user: "USERDB_SECURE"
    password: "PASS_SECURE"
    host: "superserver.com:85"
    passive: true
    scheme: sftp # default ftp

  # hooks: # Remote hooks won't work with FTP
  #   push:
  #     before:
  #       local:
  #         - 'echo "Do something locally before push"'
  #       remote:
  #         - 'echo "Do something remotely before push"'
  #     after:
  #       local:
  #         - 'echo "Do something locally after push"'
  #       remote:
  #         - 'echo "Do something remotely after push"'
  #   pull:
  #     before:
  #       local:
  #         - 'echo "Do something locally before pull"'
  #       remote:
  #         - 'echo "Do something remotely before pull"'
  #     after:
  #       local:
  #         - 'echo "Do something locally after pull"'
  #       remote:
  #         - 'echo "Do something remotely after pull"'
  #forbid:
  #   push:
  #     db: false
  #     plugins: false
  #     themes: false
  #     languages: false
  #     uploads: false
  #     mu-plugins: false
  #   pull:
  #    all: false
  #     db: false
  #     plugins: false
  #     themes: false
  #     languages: false
  #     uploads: false
  #     mu-plugins: false

# staging: # multiple environments can be specified
#   [...]
vagrant@mp`
```


wp pull -u
`vagrant@SECURE:~/www$ rm -rf wp-content/uploads/*
vagrant@SECURE:~/www$ ls wp-content/uploads/
vagrant@SECURE:~/www$ wordmove pull -u

▬▬ Using Movefile: ./movefile.yml ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

▬▬ Pulling Uploads ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
   remote | get_directory: public_html/wp-content/uploads /www/SECURE/public_html/wp-content/uploads .git/ .gitignore .gitmodules .env node_modules/ bin/ tmp/* Gemfile* Movefile movefile movefile.yml movefile.yaml wp-config.php wp-content/*.sql.gz *.orig
    ℹ️  info | lftp -c 'set ftp:list-options -a; set cmd:fail-exit true; open sftp://SECURED:%21WordMove%21@superserver.com:85; find -d 1 public_html/wp-content/uploads || mkdir -p public_html/wp-content/uploads; lcd /www/SECURE/public_html/wp-content/uploads; cd public_html/wp-content/uploads; mirror --delete --use-cache --verbose --no-perms --allow-suid --no-umask --parallel=5 --exclude-glob .git/ --exclude-glob .gitignore --exclude-glob .gitmodules --exclude-glob .env --exclude-glob node_modules/ --exclude-glob bin/ --exclude-glob tmp/* --exclude-glob Gemfile* --exclude-glob Movefile --exclude-glob movefile --exclude-glob movefile.yml --exclude-glob movefile.yaml --exclude-glob wp-config.php --exclude-glob wp-content/*.sql.gz --exclude-glob *.orig'
public_html/wp-content/uploads/                
Making directory `cache'          
Making directory `cache/wpml'                                            
Making directory `cache/wpml/twig'                                       
Making directory `2018'                                                  
Making directory `cache/wpml/twig/25'                  
Making directory `2018/07'                    
Transferring file `cache/wpml/twig/25/25fb36dfc1c3bd3239955233326b967b9fd1cc6f23620cc6beaf335bd1b59862.php'
Making directory `cache/wpml/twig/35'                     
Making directory `cache/wpml/twig/36'                                          
Transferring file `cache/wpml/twig/35/3579101563fe4d6f3143b18f1b11cbeb17bc5dd54a315d6e8801b6d40b8beecf.php'
`

**Comment by pioneerskies** [comment]
Looking at the `movefile.yml` you gave me on slack, I see that you have

```yml
ftp:
    host: "besthosting.fi:85"
```

I think we have another problem to solve and I'm investigating about it: it should be possible to pass `port` separated from `host` in `ftp` options, because in some methods I bet we have connections done to host "besthosting.fi:85", which could not be resolved by DNS since those methods expect `port` as a separate argument.

I'm working on it

**Comment by pioneerskies** [comment]
Ok we're out w/ 1.3.0.pre2 so

    gem update photocopier --pre

and configure your `ftp` section like

```yml
ftp:
    host: "example.com"
    port: 85
```

Obviously all of these new config and feature - including `doctor` command updates - will go in wordmove's documentation when photocopier will be released.

Thanks a lot for your precious patience and testing effort @xwulfus
